# Generated by Django 2.2 on 2019-09-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0006_auto_20190809_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
